version: "3.8"

services:
  redis:
    container_name: redis-dock-1
    image: redis:8.0-rc1-alpine3.21
    ports:
      - "6379:6379"

  mongo:
    container_name: mongo-dock-1
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongos
      MONGO_INITDB_ROOT_PASSWORD: 12345678

  postgres:
    container_name: postgres-dock-1
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rahasia
